import Foundation

/// Where content comes from. `.api` talks to the backend; `.bundled` reads the
/// fixtures generated by `npm run fixtures` in backend/, for previews, tests and
/// running the app before the API is deployed.
struct ContentSource: Sendable {
    var today: @Sendable (_ language: String) async throws -> Piece
    var pieces: @Sendable (_ language: String) async throws -> [PieceSummary]
    var piece: @Sendable (_ id: String, _ language: String) async throws -> Piece
    var glossary: @Sendable (_ language: String) async throws -> [GlossaryTerm]
    var composers: @Sendable (_ language: String) async throws -> [Composer]

    static let api = ContentSource(
        today: { try await APIClient.shared.today(language: $0).piece },
        pieces: { try await APIClient.shared.pieces(language: $0) },
        piece: { try await APIClient.shared.piece(id: $0, language: $1) },
        glossary: { try await APIClient.shared.glossary(language: $0) },
        composers: { try await APIClient.shared.composers(language: $0) }
    )

    static let bundled = ContentSource(
        today: { language in
            // Same plan as the API's daily_schedule (content/schedule.yaml).
            let schedule = try Fixtures.load(Fixtures.Schedule.self, "schedule", language)
            let day = Date.now.formatted(Date.ISO8601FormatStyle(timeZone: .current).year().month().day())
            let id = schedule.days[day] ?? schedule.order[0]
            return try Fixtures.load(Piece.self, "piece-\(id)", language)
        },
        pieces: { try Fixtures.load([PieceSummary].self, "pieces", $0) },
        piece: { try Fixtures.load(Piece.self, "piece-\($0)", $1) },
        glossary: { try Fixtures.load([GlossaryTerm].self, "glossary", $0) },
        composers: { try Fixtures.load([Composer].self, "composers", $0) }
    )

    static var `default`: ContentSource {
        #if DEBUG
        ProcessInfo.processInfo.environment["DC_USE_API"] == "1" ? .api : .bundled
        #else
        .api
        #endif
    }
}

nonisolated enum Fixtures {
    struct Schedule: Decodable { let start: String; let order: [String]; let days: [String: String] }

    static func load<T: Decodable>(_ type: T.Type, _ name: String, _ language: String) throws -> T {
        guard let url = Bundle.main.url(forResource: name, withExtension: "json", subdirectory: "Fixtures/\(language)")
            ?? Bundle.main.url(forResource: name, withExtension: "json", subdirectory: "Fixtures/en")
        else { throw APIError.notFound }
        return try APIClient.decode(T.self, from: Data(contentsOf: url))
    }
}
